apiVersion: containerservice.azure.com/v1
kind: AKSCluster
metadata:
  name: learnflow-aks
spec:
  resourceGroup: learnflow-rg
  location: eastus
  kubernetesVersion: "1.28"

  agentPoolProfiles:
    - name: nodepool1
      count: 3
      vmSize: Standard_D2s_v3
      osType: Linux
      mode: System

    - name: workerpool
      count: 2
      vmSize: Standard_D4s_v3
      osType: Linux
      mode: User

  networkProfile:
    networkPlugin: azure
    serviceCidr: 10.0.0.0/16
    dnsServiceIP: 10.0.0.10

  addonProfiles:
    omsagent:
      enabled: true
    azurePolicy:
      enabled: true

  identity:
    type: SystemAssigned
